name: Build image and deploy to ECS (simple)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_PREFIX: nohaalmetwally/doctor-appointment-app
    steps:
      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Set IMAGE_TAG (build number)
        run: |
          IMAGE_TAG="${IMAGE_PREFIX}:1.3.${GITHUB_RUN_NUMBER}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Using IMAGE_TAG=${IMAGE_TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            nohaalmetwally/doctor-appointment-app:latest

      # checkout terraform (public repo) into ./tf
      - name: Checkout terraform repo
        uses: actions/checkout@v4
        with:
          repository: NohaAlMetwally/doctors-app-tf
          path: tf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Show which image will be applied
        run: |
          echo "IMAGE_TAG=${IMAGE_TAG}"
          if [ -z "${IMAGE_TAG}" ]; then
            echo "ERROR: IMAGE_TAG is empty"
            exit 1
          fi

      - name: Terraform Init
        run: |
          cd tf
          terraform init -input=false

      - name: Terraform Plan & Apply (update ECS task image)
        env:
          TF_VAR_container_image: ${{ env.IMAGE_TAG }}
        run: |
          cd tf
          echo "Applying container_image = ${TF_VAR_container_image}"
          terraform plan -var "container_image=${TF_VAR_container_image}" -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan
