name: Build and push Docker image deploy to ECS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # expose job output 'image-tag' that comes from the set-tags step
    outputs:
      image-tag: ${{ steps.set-tags.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA and image tag
        id: set-tags
        run: |
          # create a short SHA and the image tag you want to push
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="nohaalmetwally/doctor-appointment-app:1.3.${GITHUB_RUN_NUMBER}"
          echo "SHORT_SHA=${SHORT_SHA}" >> $GITHUB_ENV
          # set step output so job exposes it
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "Using IMAGE_TAG=${IMAGE_TAG}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image with build number
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.set-tags.outputs.image_tag }}
            nohaalmetwally/doctor-appointment-app:latest

  deploy-infra:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout terraform repo
        uses: actions/checkout@v4
        with:
          repository: NohaAlMetwally/doctors-app-tf
          path: tf

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Show image tag passed from previous job
        run: |
          echo "Job-level output image-tag = '${{ needs.build-and-push.outputs.image-tag }}'"
          if [ -z "${{ needs.build-and-push.outputs.image-tag }}" ]; then
            echo "ERROR: image-tag is empty!"
            exit 1
          fi

      - name: Terraform Init
        run: |
          cd tf
          terraform init -input=false

      - name: Terraform Plan & Apply (update ECS task image)
        env:
          TF_VAR_container_image: ${{ needs.build-and-push.outputs.image-tag }}
        run: |
          cd tf
          echo "Applying container_image = ${TF_VAR_container_image}"
          terraform plan -var "container_image=${TF_VAR_container_image}" -out=tfplan -input=false
          terraform apply -input=false -auto-approve tfplan
